# Generated by Django 3.0.1 on 2019-12-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('dci', models.CharField(max_length=50, verbose_name='Denominação comum internacional')),
                ('dosage', models.CharField(max_length=10, verbose_name='Posologia')),
                ('generic', models.BooleanField(verbose_name='Genérico')),
                ('how_to_take', models.CharField(max_length=250, verbose_name='Forma de tomar')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('type', models.CharField(choices=[('P', 'Pacient')], max_length=1, verbose_name='Tipo')),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=9, verbose_name='Número de telemóvel')),
                ('cc', models.CharField(max_length=8, verbose_name='Número de cartão de cidadão')),
                ('nif', models.CharField(max_length=9, verbose_name='Número de identificação fiscal')),
                ('address', models.CharField(max_length=200, verbose_name='Morada')),
                ('cp', models.CharField(max_length=8, verbose_name='Código de postal')),
                ('insurance', models.CharField(blank=True, max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('type', models.CharField(choices=[('A', 'Admin'), ('M', 'Medic'), ('S', 'Secretary')], max_length=1, verbose_name='Tipo')),
                ('email', models.EmailField(max_length=256)),
                ('phone_number', models.CharField(max_length=9, verbose_name='Número de telemóvel')),
                ('cc', models.CharField(max_length=8, verbose_name='Número de cartão de cidadão')),
                ('nif', models.CharField(max_length=9, verbose_name='Número de identificação fiscal')),
                ('address', models.CharField(max_length=200, verbose_name='Morada')),
                ('numU', models.CharField(max_length=9, verbose_name='Número de utente')),
                ('cp', models.CharField(max_length=8, verbose_name='Código de postal')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditional_info', models.CharField(max_length=500, verbose_name='Notas')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Drug', verbose_name='Medicamento')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User', verbose_name='Médico')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Pacient', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=30, verbose_name='Tipo de exame')),
                ('exam_result', models.URLField(blank=True, verbose_name='Resultado do exame')),
                ('aditional_info', models.CharField(max_length=500, verbose_name='Notas')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User', verbose_name='Médico')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Pacient', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditional_info', models.CharField(max_length=500, verbose_name='Notas')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.User', verbose_name='Médico')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.Pacient', verbose_name='Paciente')),
            ],
        ),
    ]
