# Generated by Django 3.0.1 on 2019-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191223_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='patient_number',
        ),
        migrations.AddField(
            model_name='pacient',
            name='pacient_number',
            field=models.CharField(default=0, max_length=9, unique=True, verbose_name='Número de utente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.CharField(max_length=8, unique=True, verbose_name='Número de cartão de cidadão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nif',
            field=models.CharField(max_length=9, unique=True, verbose_name='Número de identificação fiscal'),
        ),
    ]
